### ISSUE TITLE
Infographic schaalbaar maken

### ISSUE THREAD

**Issue by spaceyyeti** [jfilemon/rebelzgames#1]
Het icoon van de infographic schaalt niet mee met de resolutie van het scherm. Is dit haalbaar? 
Zoniet, kan het dan wellicht iets groter?

**Comment by spaceyyeti** [comment]
![infographicstate](https://cloud.githubusercontent.com/assets/2066974/10587825/51fdca58-76a3-11e5-99c0-0b28cbd8e567.png)

**Comment by jfilemon** [comment]
closed
