### ISSUE TITLE
Knopjes met pijl aanpassen?

### ISSUE THREAD

**Issue by spaceyyeti** [jfilemon/rebelzgames#5]
Erg smaakgevoelig, dus ik laat de keuze aan @jfilemon over.
Ronde knopje is op http://html5up.net/big-picture te vinden.

![vreemdknopje](https://cloud.githubusercontent.com/assets/2066974/10589060/7ce1fe96-76a9-11e5-9a49-0d08333e1ba1.png)
![rondknopje](https://cloud.githubusercontent.com/assets/2066974/10589063/7f8c6280-76a9-11e5-8e08-ed2beeeea5e6.png)

**Comment by jfilemon** [comment]
close
